### PR TITLE
SK - Building out Results View

### PR DESCRIPTION
**Pull request by shazena**
See commit messages for even more details. There are still some things to figure out. 

1. How will we represent multiple materials on the results page? I entered multiple materials to see what it would look like, but we need a definitive answer from the designers and the rest of the team. 
2. There are some small grammar fixes to be made on the page, in the heading as well as the detailed rating score.
3. The colors of the circular progress bars need to be changed to match the icons above them. 
4. The detailed rating score section needs to be modified so that everything is aligned to the top of each table cell. This will prevent item 1 from being on a different level from the rest of the items. The text underneath is longer than the rest, so this is causing an offset. 
5. Eventually, we will need to change the rating score section from a table to bootstrap cards. Some links will be included on some resources we can use to achieve the look we're going for, lines between all cards and changing to single card per row in the mobile mode. 
6. It will probably be a good idea to make a list of all the items we need the backend to provide to us to ensure smooth connection between the two. 

Links regarding bootstrap cards having lines between them and being responsive: 

- https://getbootstrap.com/docs/4.0/components/card/#card-groups
- https://stackoverflow.com/questions/43538427/bootstrap-card-to-new-line-responsive
- https://stackoverflow.com/questions/14580346/vertical-divider-between-two-columns-in-bootstrap

### CODE REVIEW

**Comment by shazena** [comment]
There should also eventually be some sass integration so that we can use variable names for colors.

**Comment by shazena** [comment]
The text under the tiny earths are not centered, I think. That also needs fixing.

**Comment by shazena** [comment]
Also, we don't have a little dot for our overall good-bad progress bar.

**Comment by brianlee1597** [comment]
lgtm!

**Pull request merged**
